### PR TITLE
Bimorph multi version bimorph nodes

### PR DESCRIPTION
**Pull request by nicholasBimorph**
I have not been able to test this, as I don't have the Revit templates the App needs. But I am sure it will work. 

Please note:

- In the CarbonEmissionTool project I am referencing on the local machine the corresponding Revit Dll depending on the build config. You can also see that the Revit dll's are not shown directly on the References, since there is no need. Its all done automatically in the .csproj file. This is also true for referencing the CarbonEmissionTool.Compatibility.dll.
- The same approach is applied to the RevitAddin project.
- The CarbonEmissionTool.Compatibility project is the only one that references the Revit API from Nuget. This references the lowest Revit version the App will target. This pull request targets 2019. If you want to target a lower version, just reference a previous nuget package of the Revit API as well as make a new build config via the _Configuration Manager_. As well as update the CarbonEmissionTool  and CarbonEmissionTool.Compatibility  .csproj files accordingly. I have left some comments there as guides.

### CODE REVIEW

**Comment by benrobinson20** [comment]
Hi Nick, I have found a issue when trying to run the app in pre 2021 Revit version. Whenever the method ToDecimalFeet is called it fails  due to the ForgeTypeId. What i dont understand is why it is failing before it has even stepped inside the method as it shouldn't be failing at all.  I've tried a few things but cant get my head around why its not working.
image

Also the Revit templates for testing are located in the main repo folder called 'Revit Templates' 
image

If you open one of these template files if you change the design option to 'Carbon Material Library' you can run the HBERT from this for testing. 

image

**Comment by nicholasBimorph** [comment]
@benrobinson20 commited changes. When building select Debug2021. If you are building in Release, just select Release as it will target Revit 2021.

**Comment by benrobinson20** [comment]
Hey @nicholasBimorph we have figured out what was causing the issue.  The ToDecimalFeet method was always causing an exception it seems because  it was all in the same method. We have separated the Forge handling into a new method and this has stopped the exception. 

I haven't come across a issue like this before and dont no if it relates to it being an extension method?
Or when you call a method does it actual 'preload' everything in the method hence the exception even though its within an if statement



image

**Comment by benrobinson20** [comment]
Closed as further updates have been made in pull request #25

**Pull request closed without merging**
